name: dev_template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Routing
  go_router: ^14.1.4

  # Dependency Injection
  get_it: ^7.7.0

  # Network
  dio: ^5.4.3+1

  # Localization
  easy_localization: ^3.0.7
  json_annotation: ^4.9.0

  # Core
  equatable: ^2.0.5

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  # Theme
  flex_color_scheme: ^7.3.1

  # Cache
  hydrated_bloc: ^9.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # Path Provider
  path_provider: ^2.1.3

  change_app_package_name: ^1.2.0
  rename_app: ^1.4.0
  lottie: ^3.1.2
  permission_handler: ^11.3.1


  # File Picker
  file_picker: ^8.0.3

  # Image Picker
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.10
  json_serializable: ^6.8.0


  # Linting
  very_good_analysis: ^5.1.0




flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/shoes/
    - assets/lottie/
    - assets/splash/
    - assets/images/